data <- read.csv('AustinCityLimits.csv')

# 1) How many artists are in this dataset?
length(data$Artist)
#116

# 2) How many of the first 10 artists in the dataset were Grammy winners?
first10 <- data[1:10,]
sum(first10$Grammy=='Y')
# 4

# 3) What genre was played by the first female artist in the dataset who was over 60 years of age?
female <- data[data$Gender=='F',]
femaleOver60 <- female[female$Age>60,]
femaleOver60[1, 9]
# Jazz/Blues

# Create tables of marginal distributions
genre <- table(data$Genre)
genre
gender <- table(data$Gender)
gender

# Create contingency table 
twoway <- table (data$Gender,data$Genre)
twoway

# Visualize the counts
barplot(twoway, legend=T, beside=T)

# Calculate P(A): the probability of each genre being played
prop.table(genre)

# Calculate P(A|B): the probability of each genre being played, given the artistfs gender
prop.table(twoway,1)

# 1) How many columns will be present in the table generated by the following line of code?
# gender <- table(data$Gender)

# 2 

# 2) This code produces a bar chart with both a legend and side-by-side bars for each gender:
#         barplot(twoway, legend=TRUE, beside=TRUE)
# 
# What would the code look like if we wanted to keep the legend but stack the bars (instead of set them side-by-side)?

# barplot(twoway, legend=TRUE)

# 3) This line of code will produce four values, one for each genre of music:
#         prop.table(genre)
# What value should you get if you sum the four values together?

# 1.00

# 4) What does the value "1" refer to in this line of code:
#         prop.table(twoway,1)

# The number 1 references the first variable (gender) listed in the contingency table code.

# 1) How many male/female artists are in the Austin City Limits dataset?
male <- data[data$Gender=='M',]
length(male$Artist)
# 81

# 2) How many female artists are in the Austin City Limits dataset?
length(female$Artist)
# 35

# 3) To determine the proportion of jazz performers that were male, you would divide ________ by ________.
jazz <- data[data$Genre=='Jazz/Blues',]
jazzMale <- jazz[jazz$Gender=='M',]
# 7/13

# 4) To determine the proportion of males that performed jazz, you would divide ________ by ________.
maleJazz <- male[male$Genre=='Jazz/Blues',]
# 7/81

# 5) Which table should you look at to determine how many artists performed rock/folk/indie music: genre or gender?
# genre

# 6) How many artists performed rock/folk/indie music?
rock <- data[data$Genre=='Rock/Folk/Indie',]
length(rock$Artist)
# 68

# 7) Which of these lines of code provides the probability that a randomly selected artist from the dataset performed rock/folk/indie music?
# prop.table(genre)

# 8) What is the probability that a randomly selected artist from the dataset performed rock/folk/indie music?
prop.table(genre)
#  0.586

# 9) Which of these lines of code provides the probability that a randomly selected female artist performed rock/folk/indie music?
# prop.table(twoway,1)

# 10) What is the probability that a randomly selected female artist performed rock/folk/indie music? 
prop.table(twoway,1)
# 0.343


#CONCLUSIONS
# The music played on Austin City Limits was grouped into four genres, including Country, Jazz, Rock and Singer-Songwriter.   
# Rock was the most frequently played genre, performed by 58.6% of the Austin City Limits artists. 
# Among female artists, however, only 34.3% of the artists played Rock music. This difference between the 
# marginal and   conditional - correct probabilities suggests that gender and genre are not independent. This difference 
# was also evident in the bar plots, where it was evident that females were more likely to perform in the Singer-Songwriter 
# category than their male counterparts.
# 
